// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Y10Nv90WkBdO2Am-gx9wPgFTk-dl55k',
    appId: '1:199131897060:web:c8010510ae6f2356f1a0f1',
    messagingSenderId: '199131897060',
    projectId: 'app-prestamo-e-inventario',
    authDomain: 'app-prestamo-e-inventario.firebaseapp.com',
    storageBucket: 'app-prestamo-e-inventario.appspot.com',
    measurementId: 'G-LE3J602G2P',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6Y10Nv90WkBdO2Am-gx9wPgFTk-dl55k',
    appId: '1:199131897060:web:c8010510ae6f2356f1a0f1',
    messagingSenderId: '199131897060',
    projectId: 'app-prestamo-e-inventario',
    authDomain: 'app-prestamo-e-inventario.firebaseapp.com',
    storageBucket: 'app-prestamo-e-inventario.appspot.com',
    measurementId: 'G-LE3J602G2P',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyA6Y10Nv90WkBdO2Am-gx9wPgFTk-dl55k',
    appId: '1:199131897060:web:c8010510ae6f2356f1a0f1',
    messagingSenderId: '199131897060',
    projectId: 'app-prestamo-e-inventario',
    authDomain: 'app-prestamo-e-inventario.firebaseapp.com',
    storageBucket: 'app-prestamo-e-inventario.appspot.com',
    measurementId: 'G-LE3J602G2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCILU5Jltl5xNodfnCgBeHUCxqY58LTWYY',
    appId: '1:199131897060:android:fa16a9d039930f41f1a0f1',
    messagingSenderId: '199131897060',
    projectId: 'app-prestamo-e-inventario',
    storageBucket: 'app-prestamo-e-inventario.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgC7XKCK4vJc6AfS_NMfZ8vyn_kF5LXvY',
    appId: '1:199131897060:ios:1e0848ab5fd90abff1a0f1',
    messagingSenderId: '199131897060',
    projectId: 'app-prestamo-e-inventario',
    storageBucket: 'app-prestamo-e-inventario.appspot.com',
    iosClientId:
        '199131897060-n5k2j4mvldu2ru8efsh68nvhsk6an23i.apps.googleusercontent.com',
    iosBundleId: 'com.example.appGestionPrestamoInventario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgC7XKCK4vJc6AfS_NMfZ8vyn_kF5LXvY',
    appId: '1:199131897060:ios:1e0848ab5fd90abff1a0f1',
    messagingSenderId: '199131897060',
    projectId: 'app-prestamo-e-inventario',
    storageBucket: 'app-prestamo-e-inventario.appspot.com',
    iosClientId:
        '199131897060-n5k2j4mvldu2ru8efsh68nvhsk6an23i.apps.googleusercontent.com',
    iosBundleId: 'com.example.appGestionPrestamoInventario',
  );
}
